language: python
sudo: false
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install python-coveralls==2.7.0"
  - "pip install -r requirements_test.txt"
  - "pip install -r requirements.txt"
before_script:
  - "coverage erase"
script:
  - "py.test --cov=peewee_validates.py"
after_success:
  - "coverage report"
  - "coveralls"
